characters = [{
    "weight":"8",
    "acceleration":"0",
    "drift":"0",
    "handling":"6",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"0",
    "name":"Baby Mario",
    "size":"S"
  },{
    "weight":"8",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"5",
    "name":"Baby Luigi",
    "size":"S"
  },{
    "weight":"6",
    "acceleration":"3",
    "drift":"0",
    "handling":"3",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"3",
    "name":"Baby Peach",
    "size":"S"
  },{
    "weight":"6",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"3",
    "speed":"5",
    "name":"Baby Daisy",
    "size":"S"
  },{
    "weight":"0",
    "acceleration":"6",
    "drift":"6",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"0",
    "name":"Toad",
    "size":"S"
  },{
    "weight":"0",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"6",
    "mini_turbo":"0",
    "speed":"3",
    "name":"Toadette",
    "size":"S"
  },{
    "weight":"0",
    "acceleration":"0",
    "drift":"0",
    "handling":"3",
    "off_road":"0",
    "mini_turbo":"6",
    "speed":"0",
    "name":"Koopa Troopa",
    "size":"S"
  },{
    "weight":"0",
    "acceleration":"3",
    "drift":"3",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"6",
    "speed":"0",
    "name":"Dry Bones",
    "size":"S"
  },{
    "weight":"3",
    "acceleration":"0",
    "drift":"3",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"3",
    "speed":"3",
    "name":"Mii (Light)",
    "size":"S"
  },{
    "weight":"6",
    "acceleration":"2",
    "drift":"3",
    "handling":"2",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"0",
    "name":"Mario",
    "size":"M"
  },{
    "weight":"6",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"2",
    "name":"Luigi",
    "size":"M"
  },{
    "weight":"0",
    "acceleration":"5",
    "drift":"6",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"2",
    "name":"Peach",
    "size":"M"
  },{
    "weight":"0",
    "acceleration":"0",
    "drift":"0",
    "handling":"2",
    "off_road":"0",
    "mini_turbo":"3",
    "speed":"4",
    "name":"Daisy",
    "size":"M"
  },{
    "weight":"3",
    "acceleration":"0",
    "drift":"3",
    "handling":"0",
    "off_road":"5",
    "mini_turbo":"0",
    "speed":"0",
    "name":"Yoshi",
    "size":"M"
  },{
    "weight":"3",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"3",
    "mini_turbo":"5",
    "speed":"0",
    "name":"Birdo",
    "size":"M"
  },{
    "weight":"0",
    "acceleration":"3",
    "drift":"3",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"5",
    "speed":"0",
    "name":"Diddy Kong",
    "size":"M"
  },{
    "weight":"0",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"3",
    "mini_turbo":"3",
    "speed":"0",
    "name":"Bowser Jr.",
    "size":"M"
  },{
    "weight":"3",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"3",
    "mini_turbo":"3",
    "speed":"3",
    "name":"Mii (Medium)",
    "size":"M"
  },{
    "weight":"3",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"3",
    "mini_turbo":"6",
    "speed":"0",
    "name":"Wario",
    "size":"L"
  },{
    "weight":"0",
    "acceleration":"6",
    "drift":"5",
    "handling":"0",
    "off_road":"3",
    "mini_turbo":"0",
    "speed":"0",
    "name":"Waluigi",
    "size":"L"
  },{
    "weight":"3",
    "acceleration":"2",
    "drift":"0",
    "handling":"2",
    "off_road":"0",
    "mini_turbo":"3",
    "speed":"0",
    "name":"Donkey Kong",
    "size":"L"
  },{
    "weight":"5",
    "acceleration":"0",
    "drift":"3",
    "handling":"0",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"2",
    "name":"Bowser",
    "size":"L"
  },{
    "weight":"0",
    "acceleration":"0",
    "drift":"0",
    "handling":"5",
    "off_road":"3",
    "mini_turbo":"0",
    "speed":"0",
    "name":"King Boo",
    "size":"L"
  },{
    "weight":"0",
    "acceleration":"0",
    "drift":"0",
    "handling":"3",
    "off_road":"0",
    "mini_turbo":"3",
    "speed":"3",
    "name":"Rosalina",
    "size":"L"
  },{
    "weight":"0",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"3",
    "mini_turbo":"0",
    "speed":"4",
    "name":"Funky Kong",
    "size":"L"
  },{
    "weight":"0",
    "acceleration":"0",
    "drift":"0",
    "handling":"0",
    "off_road":"6",
    "mini_turbo":"6",
    "speed":"0",
    "name":"Dry Bowser",
    "size":"L"
  },{
    "weight":"0",
    "acceleration":"3",
    "drift":"3",
    "handling":"3",
    "off_road":"0",
    "mini_turbo":"0",
    "speed":"3",
    "name":"Mii (Heavy)",
    "size":"L"
  }];
